apiVersion: skaffold/v2beta29
kind: Config

profiles:
  - name: dev
    build:
      local:
        push: true
      artifacts:
        - image: saturn203/demo-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            #  fromImage: adoptopenjdk/openjdk11
            fromImage: openjdk:11.0.11-jre-slim
    deploy:
      kubectl:
        manifests:
          - k8s/dev/*.yaml
      

  
    portForward:
    - resourceType: deployment
      resourceName: demo-api
      namespace: api
      port: 8080
      localPort: 9000 # *Optional*    

  - name: kind
    build:
      local:
        push: false
      artifacts:
        - image: demo-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"
            #  fromImage: adoptopenjdk/openjdk11
            fromImage: openjdk:11.0.11-jre-slim
    deploy:
      kubectl:
        manifests:
          - k8s/kind/*.yaml
      

  
    portForward:
    - resourceType: service
      resourceName: demo-api-svc
      namespace: api
      port: 8080
      localPort: 9320 # *Optional*                

  
      
