##############
### local
##############

server:
  port: 9320

spring:
  datasource:    
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/samp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&useUnicode
    username: root
    password: 1234
    hikari: 
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  jpa:
    
    show-sql: true
    properties:
        hibernate:
            format_sql: true
    hibernate:
        ddl-auto: none    # create, update , none

springdoc:
  api-docs:
    path: /v3/api-docs
    groups.enabled: true
  swagger-ui:
      enabled: true
      path: /swagger
      displayRequestDuration: false
      groups-order: DESC